[build]
  command = "npm run build"
  publish = "dist"  # If using a build system, otherwise it could be "src"

[dev]
  command = "npm start"
  port = 3000
  framework = "#custom"  # If using a custom setup

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
